version: '3.8'

services:
  userservice:
    image: userservice
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      userservice-postgres-db:
        condition: service_healthy
    environment:
      ConnectionStrings__Postgres: "User ID=postgres;Password=userservicepass;Host=userservice-postgres-db;Port=5432;Database=userservice;"
    ports:
      - "36801:36801"

  userservice-postgres-db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: userservicepass
      POSTGRES_DB: userservice
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:

# docker-compose up -d
# docker-compose down -v --rmi all --remove-orphans